# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZY4jydWMBPKP05tO6z0tDZk4fdQRA0Q
"""

import tensorflow as tf
import numpy as np
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)
# If you want to be specific, you can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)
np.array(rank_2_tensor)
rank_2_tensor.numpy()

"""Tensors are divided into dimensions
scalar-0D
vector-1D
Matrix -2D

"""

import tensorflow as tf
import numpy as np
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])

print(rank_3_tensor)

"""Operations of tensors are -constant,zeroes"""

import tensorflow as tf

scalar_tensor = tf.constant(5)
vector_tensor = tf.constant([1, 2, 3, 4])

matrix_tensor = tf.constant([[1, 2], [3, 4]])
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
zeros_tensor = tf.zeros([3, 3])
ones_tensor = tf.ones([2, 2])
print(scalar_tensor)
print(vector_tensor)
print(matrix_tensor)

"""ADD MULTIPLY AND BASIC OPERATIONS ON 2D"""

a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2], dtype=tf.int32)`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

"""MAX od c and index of max ,softmax for converting raw scores into probabilities


"""

c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.math.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))
tf.convert_to_tensor([1,2,3])
tf.reduce_max(np.array([1,2,3]))

rank_4_tensor = tf.zeros([3, 2, 4, 5])
print(rank_4_tensor)

print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

import tensorflow as tf

a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

print(a)
print("Shape:", a.shape)

#RESHAPE
b = tf.reshape(a, (3, 2))
print(b)
print("Shape:", b.shape)

#TRASPOSE
t = tf.transpose(a)
print(t)
print("Shape:", t.shape)

#BROADCASTING
m = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

v = tf.constant([10, 20, 30])

result = m + v
print(result)